/*
DIM1/data/ender_dragon_fight.dat
data/custom_boss_events.dat
data/game_rules.dat
data/scheduled_events.dat
data/wandering_trader.dat
data/weather.dat
data/world_clocks.dat
data/world_gen_settings.dat
*/
